# Generated by Django 5.0.3 on 2024-04-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_user_is_admin_user_is_buyer_user_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
    ]
