# Generated by Django 5.0.3 on 2024-04-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_category_client_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='principal_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='secondary_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
