# Generated by Django 5.0.3 on 2024-04-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_alter_client_principal_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSellerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.client')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.seller')),
            ],
        ),
    ]
