# Generated by Django 5.0.3 on 2024-04-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0007_clientsellerrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='code_seller',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
