# Generated by Django 5.0.3 on 2024-04-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0008_alter_seller_code_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='categories/default-category.jpeg', upload_to='categories/'),
        ),
    ]
