# Generated by Django 5.0.3 on 2024-04-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0012_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
