# Generated by Django 5.0.3 on 2024-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0017_client_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_cart',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
