# Generated by Django 5.0.3 on 2024-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0018_client_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(blank=True, to='intro.product'),
        ),
    ]
