# Generated by Django 5.0.3 on 2024-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0019_remove_sale_product_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
