# Generated by Django 5.0.3 on 2024-04-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0020_sale_is_delivered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client_cart',
        ),
    ]
