# Generated by Django 5.0.3 on 2024-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0023_alter_sale_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
