# Generated by Django 5.0.3 on 2024-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0025_remove_sale_is_done_clientsellerrelation_done_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsellerrelation',
            name='Product_Quantity',
            field=models.ManyToManyField(blank=True, to='intro.product_quantity'),
        ),
    ]
