# Generated by Django 5.0.3 on 2024-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0026_clientsellerrelation_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='clientsellerrelation',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
