# Generated by Django 5.0.3 on 2024-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0027_remove_sale_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsellerrelation',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
