# Generated by Django 5.0.3 on 2024-04-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0028_clientsellerrelation_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsellerrelation',
            name='Product_Quantity',
            field=models.ManyToManyField(to='intro.product_quantity'),
        ),
        migrations.AlterField(
            model_name='clientsellerrelation',
            name='total',
            field=models.FloatField(),
        ),
    ]
