# Generated by Django 5.0.4 on 2024-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0029_alter_clientsellerrelation_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(default='Sin Clasificar', max_length=40),
        ),
    ]
