# Generated by Django 5.0.4 on 2024-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0030_client_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(default='Sin Clasificar', max_length=50),
        ),
    ]
